spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
management.endpoint.health.show-details=always

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=${REDIS_EMAIL_DB}

cache.email.ttl=${CACHE_EMAIL_TTL}
cache.email.key.prefix=${CACHE_EMAIL_KEY_PREFIX}

hogs.api.base.url=${HOGS_API_BASE_URL}
hogs.api.bot.login=${HOGS_API_LOGIN}
hogs.api.bot.password=${HOGS_API_PASSWORD}
hogs.api.arsHash=${HOGS_API_ARS_HASH}


abstractapi.api.key=${ABSTRACT_API_KEY}
abstractapi.base.url=${ABSTRACT_BASE_URL}


logging.level.org.springframework.data.redis=DEBUG
logging.level.org.springframework.data.redis.core=TRACE
logging.level.io.lettuce.core=DEBUG