services:
  web:
    container_name: "ars_backend_email_verify"
#    restart: on-failure
    ports:
      - "${APP_PUBLIC_PORT}:8081"
    depends_on:
      - redis
      - mongodb
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8081
      SPRING_DATA_MONGODB_URI: ${MONGO_EMAIL_URI}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_EMAIL_DB: ${REDIS_EMAIL_DB}
      CACHE_EMAIL_TTL: ${CACHE_EMAIL_TTL}
      CACHE_EMAIL_KEY_PREFIX: ${CACHE_EMAIL_KEY_PREFIX}
      ABSTRACT_API_KEY: ${ABSTRACT_API_KEY}
      ABSTRACT_BASE_URL: ${ABSTRACT_BASE_URL}
      HOGS_API_BASE_URL: ${HOGS_API_BASE_URL}
      HOGS_API_ARS_HASH: ${HOGS_API_ARS_HASH}
      HOGS_API_LOGIN: ${HOGS_API_LOGIN}
      HOGS_API_PASSWORD: ${HOGS_API_PASSWORD}
  redis:
    container_name: "ars_backend_redis"
    image: redis:7.4.6-alpine
    restart: on-failure
  mongodb:
    container_name: "ars_backend_email_mongodb"
    image: mongo:7.0.31
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_EMAIL_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_EMAIL_PASSWORD}