services:
  web:
    container_name: "ars_frontend_email_verify"
    restart: on-failure
    ports:
      - "${APP_PUBLIC_PORT}:3001"
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NEXT_PUBLIC_API_URL: "${NEXT_PUBLIC_API_URL}"
