### -----------------------
### Mongo (Testcontainers)
### -----------------------
spring.data.mongodb.uri=mongodb://localhost:27017/test

### -----------------------
### Redis (Testcontainers)
### -----------------------
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.password=

### -----------------------
### Cache config (REQUIRED)
### -----------------------
cache.email.ttl=60s
cache.email.key.prefix=test_email

### -----------------------
### HOGS API (WireMock)
### -----------------------
hogs.api.base.url=http://localhost:8080
hogs.api.bot.login=test
hogs.api.bot.password=test
hogs.api.arsHash=test-hash

### -----------------------
### Abstract API (WireMock)
### -----------------------
abstractapi.base.url=http://localhost:8080
abstractapi.api.key=test-key

### -----------------------
### Logging (opcjonalne)
### -----------------------
logging.level.org.springframework.data.redis=INFO
logging.level.io.lettuce.core=INFO
